module.exports = {
  AzureWebJobsStorage: 'AzureWebJobsStorage',
  AW_AUTH_HEADER: 'AW_AUTH_HEADER',
  AW_EXTRACT_CONTAINER: 'AW_EXTRACT_CONTAINER',
  AW_DOMAIN: 'AW_DOMAIN',
  AW_TENANT_CODE: 'AW_TENANT_CODE'
}
