module.exports = {
  AzureWebJobsStorage: 'AzureWebJobsStorage',
  AW_AUTH_HEADER: 'AW_AUTH_HEADER',
  AW_DOMAIN: 'AW_DOMAIN',
  AW_TENANT_CODE: 'AW_TENANT_CODE',
  DATA_EXTRACT_CONTAINER: 'DATA_EXTRACT_CONTAINER',
  DATA_IMPORT_CONTAINER: 'DATA_IMPORT_CONTAINER',
  DATA_SOURCES_CONTAINER: 'DATA_SOURCES_CONTAINER'
}
